# Generated by Django 5.0.14 on 2026-07-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='title',
        ),
    ]
