# Generated by Django 5.0.14 on 2026-07-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallerycategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gallery.gallerycategory')),
            ],
            options={
                'unique_together': {('category', 'language')},
            },
        ),
    ]
