# Generated by Django 5.0.14 on 2026-07-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_remove_service_canonical_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, max_length=500)),
                ('short_description', models.TextField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Service Translations',
                'unique_together': {('service', 'language')},
            },
        ),
    ]
