# Generated by Django 5.0.14 on 2026-07-22 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('message', models.TextField()),
                ('request_type', models.CharField(choices=[('contact', 'Contact'), ('consultation', 'Consultation'), ('design_request', 'Design Request')], db_index=True, default='contact', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('on_grid', 'On Grid'), ('off_grid', 'Off Grid'), ('hybrid', 'Hybrid'), ('large_scale', 'Large Scale')], db_index=True, max_length=20)),
                ('estimated_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='kW', max_digits=10, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_design', 'In Design'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
