# Generated by Django 5.0.14 on 2026-07-22 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_contact', 'New Contact'), ('contact_status_change', 'Contact Status Change'), ('new_project_inquiry', 'New Project Inquiry'), ('project_inquiry_status_change', 'Project Inquiry Status Change'), ('system', 'System'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
