# Generated by Django 5.2.16 on 2026-09-21 05:51

import apps.homepage.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_articletranslation'),
        ('media_manager', '0004_alter_mediafile_file_alter_mediafile_file_type'),
        ('products', '0002_slughistory'),
        ('projects', '0003_projecttranslation'),
        ('services', '0003_servicetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('featured_products', 'Featured Products'), ('categories', 'Categories'), ('services', 'Services'), ('calculator', 'Calculator'), ('projects', 'Projects'), ('articles', 'Articles'), ('contact', 'Contact')], db_index=True, max_length=32, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HomepageArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_entry', to='articles.article')),
            ],
            options={
                'verbose_name': 'Homepage Article',
                'verbose_name_plural': 'Homepage Articles',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_entry', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Homepage Category',
                'verbose_name_plural': 'Homepage Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_eyebrow', models.CharField(blank=True, default='', max_length=255)),
                ('hero_primary_cta_label', models.CharField(blank=True, default='مشاهده محصولات', max_length=255)),
                ('hero_primary_cta_url', models.CharField(blank=True, default='/products', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('hero_primary_cta_enabled', models.BooleanField(default=True)),
                ('hero_secondary_cta_label', models.CharField(blank=True, default='محاسبه سیستم خورشیدی', max_length=255)),
                ('hero_secondary_cta_url', models.CharField(blank=True, default='/calculator', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('hero_secondary_cta_enabled', models.BooleanField(default=True)),
                ('calculator_cta_label', models.CharField(blank=True, default='شروع محاسبه', max_length=255)),
                ('calculator_cta_url', models.CharField(blank=True, default='/calculator', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('contact_cta_label', models.CharField(blank=True, default='تماس با ما', max_length=255)),
                ('contact_cta_url', models.CharField(blank=True, default='/contact', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('contact_secondary_cta_label', models.CharField(blank=True, default='درخواست قیمت', max_length=255)),
                ('contact_secondary_cta_url', models.CharField(blank=True, default='/contact', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('articles_count', models.PositiveIntegerField(default=3)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots', models.CharField(choices=[('index_follow', 'Index, Follow'), ('noindex_follow', 'Noindex, Follow'), ('index_nofollow', 'Index, Nofollow'), ('noindex_nofollow', 'Noindex, Nofollow')], default='index_follow', max_length=20)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_as_og', to='media_manager.mediafile')),
            ],
            options={
                'verbose_name': 'Homepage Config',
                'verbose_name_plural': 'Homepage Config',
            },
        ),
        migrations.CreateModel(
            name='HomepageFeaturedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_feature', to='products.product')),
            ],
            options={
                'verbose_name': 'Homepage Featured Product',
                'verbose_name_plural': 'Homepage Featured Products',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_entry', to='projects.project')),
            ],
            options={
                'verbose_name': 'Homepage Project',
                'verbose_name_plural': 'Homepage Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_entry', to='services.service')),
            ],
            options={
                'verbose_name': 'Homepage Service',
                'verbose_name_plural': 'Homepage Services',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageVisual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('link_url', models.CharField(blank=True, default='', max_length=500, validators=[apps.homepage.models.validate_cta_url])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_visuals', to='media_manager.mediafile')),
            ],
            options={
                'verbose_name': 'Homepage Visual',
                'verbose_name_plural': 'Homepage Visuals',
                'ordering': ['order', 'id'],
            },
        ),
    ]
