# Generated by Django 5.0.14 on 2026-07-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
