# Generated by Django 5.0.14 on 2026-07-22 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('daily_consumption', models.DecimalField(decimal_places=2, help_text='kWh/day', max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('irradiation', models.DecimalField(decimal_places=2, help_text='kWh/m²/day', max_digits=5)),
                ('battery_type', models.CharField(choices=[('lead_acid', 'Lead Acid'), ('lithium', 'Lithium'), ('tubular', 'Tubular')], max_length=20)),
                ('system_type', models.CharField(choices=[('on_grid', 'On Grid'), ('off_grid', 'Off Grid'), ('hybrid', 'Hybrid')], max_length=20)),
                ('panel_capacity', models.DecimalField(decimal_places=2, help_text='kW', max_digits=10)),
                ('panel_count', models.IntegerField()),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='Ah', max_digits=10)),
                ('inverter_power', models.DecimalField(decimal_places=2, help_text='kW', max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=0, help_text='IRR', max_digits=15)),
                ('roi_years', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
