# Generated by Django 5.0.14 on 2026-07-22 14:43

import apps.media_manager.models
import django.core.validators
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.media_manager.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'mp4', 'avi', 'mov', 'mkv', 'zip', 'rar', 'txt'])])),
                ('thumbnail', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('original_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], db_index=True, max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('subfolder', models.CharField(default='general', max_length=100)),
                ('is_temp', models.BooleanField(db_index=True, default=False)),
                ('upload_completed', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
