# Generated by Django 5.2.16 on 2026-09-19 05:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0004_alter_mediafile_file_alter_mediafile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots', models.CharField(choices=[('index_follow', 'Index, Follow'), ('noindex_follow', 'No Index, Follow'), ('index_nofollow', 'Index, No Follow'), ('noindex_nofollow', 'No Index, No Follow')], default='index_follow', max_length=20)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_as_cover', to='media_manager.mediafile')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_as_og', to='media_manager.mediafile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], default='text', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_definitions', to='products.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden')], db_index=True, default='public', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots', models.CharField(choices=[('index_follow', 'Index, Follow'), ('noindex_follow', 'No Index, Follow'), ('index_nofollow', 'Index, No Follow'), ('noindex_nofollow', 'No Index, No Follow')], default='index_follow', max_length=20)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_og', to='media_manager.mediafile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Category Translations',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('catalog', 'Catalog'), ('datasheet', 'Datasheet'), ('installation_guide', 'Installation Guide'), ('spec_sheet', 'Specification Sheet'), ('other', 'Other')], default='catalog', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_documents', to='media_manager.mediafile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('caption', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='media_manager.mediafile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_cover', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_mode', models.CharField(choices=[('contact', 'Contact for Price'), ('regular', 'Regular Price'), ('discounted', 'Discounted Price'), ('hidden', 'Hidden Price')], default='contact', max_length=20)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, default='', max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('ar', 'Arabic'), ('en', 'English')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=500)),
                ('short_description', models.TextField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('features', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Translations',
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('similar', 'Similar'), ('accessory', 'Accessory'), ('recommended', 'Recommended')], default='related', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='products.product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.CharField(blank=True, default='', max_length=1000)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'definition'), name='uniq_product_attribute')],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'is_active', 'sort_order'], name='products_pr_parent__859a80_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='productcategory_no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'visibility', 'is_active'], name='products_pr_status_29ee15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured'], name='products_pr_status_28f1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategorytranslation',
            unique_together={('category', 'language')},
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product',), name='uniq_product_cover'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('regular_price__isnull', True), ('regular_price__gte', 0), _connector='OR'), name='price_regular_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='price_sale_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('regular_price__isnull', True), ('sale_price__lte', models.F('regular_price')), _connector='OR'), name='price_sale_lte_regular'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='price_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('discount_value__lte', 100), _connector='OR'), name='price_percent_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='price_window_valid'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product', 'section', 'sort_order'], name='products_pr_product_4503a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language')},
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.UniqueConstraint(fields=('from_product', 'to_product'), name='uniq_product_relation'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('from_product', models.F('to_product')), _negated=True), name='relation_no_self_reference'),
        ),
    ]
