# Generated by Django 5.2.16 on 2026-09-20 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('product_category', 'Product Category')], db_index=True, max_length=20)),
                ('object_id', models.UUIDField(db_index=True)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=5)),
                ('old_slug', models.SlugField(allow_unicode=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['target_type', 'object_id'], name='products_sl_target__9b2a32_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'language', 'old_slug'), name='uniq_slug_history_target_lang_slug')],
            },
        ),
    ]
