# Generated by Django 5.0.14 on 2026-07-22 14:43

import django.core.validators
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$')], verbose_name='phone number')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('website_admin', 'Website Admin'), ('content_manager', 'Content Manager'), ('engineer', 'Engineer'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='role')),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, default='', verbose_name='biography')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'role'], name='users_user_email_8fcb62_idx'), models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx')],
            },
        ),
    ]
