# Generated by Django 5.0.14 on 2026-07-22 14:43

import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('publish', 'Publish'), ('archive', 'Archive'), ('status_change', 'Status Change'), ('role_change', 'Role Change'), ('password_reset_request', 'Password Reset Request')], db_index=True, max_length=30)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('object_repr', models.CharField(blank=True, default='', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='ابر انرژی', max_length=255)),
                ('company_name_en', models.CharField(default='AbrEnergy', max_length=255)),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='company/logo/')),
                ('favicon', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='company/favicon/')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number_2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('telegram', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('youtube', models.URLField(blank=True, default='')),
                ('hero_title', models.CharField(blank=True, default='', max_length=500)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('hero_background_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='company/hero/')),
                ('about_us', models.TextField(blank=True, default='')),
                ('about_us_en', models.TextField(blank=True, default='')),
                ('default_meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('default_meta_description', models.TextField(blank=True, default='')),
                ('default_keywords', models.TextField(blank=True, default='')),
                ('site_url', models.URLField(blank=True, default='https://abrenv.com')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
